# Generated by Django 6.1 on 2026-08-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('status', models.CharField(max_length=50)),
                ('expected_delivery', models.DateField()),
            ],
        ),
    ]
